package com.ciaac.minecraft.minigames.colorfloor;
import com.ciaac.minecraft.minigames.hotpotato.OperationId; import java.time.Instant; import java.util.*; import java.util.random.RandomGeneratorFactory;
public final class ColorFloorGame{
 private final UUID id;private final ColorFloorConfig config;private final List<FloorColor> targets;private final LinkedHashSet<UUID> roster=new LinkedHashSet<>(),live=new LinkedHashSet<>();private final Map<UUID,Integer> eliminations=new HashMap<>();private final Set<OperationId> ops=new HashSet<>();private ColorFloorPhase phase=ColorFloorPhase.DISABLED;private int round;private ColorFloorResult result;
 public ColorFloorGame(UUID id,ColorFloorConfig c){this.id=Objects.requireNonNull(id);config=Objects.requireNonNull(c);var r=RandomGeneratorFactory.<java.util.random.RandomGenerator>of("L64X128MixRandom").create(c.seed());var p=new ArrayList<FloorColor>();for(int i=0;i<c.rounds();i++)p.add(c.palette().get(r.nextInt(c.palette().size())));targets=List.copyOf(p);}
 public synchronized ColorFloorPhase phase(){return phase;}public synchronized Set<UUID> livePlayers(){return Set.copyOf(live);}public synchronized List<FloorColor> targets(){return targets;}public synchronized int round(){return round;}public synchronized Optional<ColorFloorResult> result(){return Optional.ofNullable(result);}
 public synchronized void open(OperationId o){mutate(o,ColorFloorPhase.WAITING);}public synchronized void join(UUID p,OperationId o){require(ColorFloorPhase.WAITING,o);Objects.requireNonNull(p);if(roster.contains(p)||roster.size()>=config.maximumPlayers())throw new IllegalStateException("roster full or duplicate");accept(o);roster.add(p);}
 public synchronized void start(OperationId o){require(ColorFloorPhase.WAITING,o);if(roster.size()<config.minimumPlayers())throw new IllegalStateException("minimum players not reached");accept(o);live.addAll(roster);round=1;phase=ColorFloorPhase.REACTION;}
 public synchronized FloorColor target(){if(round<1)throw new IllegalStateException("not started");return targets.get(round-1);}public synchronized void resolve(Set<UUID> standing,OperationId o){require(ColorFloorPhase.REACTION,o);if(standing==null||!live.containsAll(standing))throw new IllegalArgumentException("standing players invalid");accept(o);var gone=new HashSet<>(live);gone.removeAll(standing);gone.forEach(p->eliminations.merge(p,1,Integer::sum));live.retainAll(standing);if(live.size()<=1||round>=config.rounds()){result=new ColorFloorResult(id,config.rulesetRevision(),Set.copyOf(live),round,eliminations,live.isEmpty()?"ALL_ELIMINATED":"COMPLETED");phase=ColorFloorPhase.FINISHING;}else{round++;phase=ColorFloorPhase.REACTION;}}
 public synchronized void recover(OperationId o){if(phase==ColorFloorPhase.CLOSED||phase==ColorFloorPhase.DISABLED)throw new IllegalStateException("cannot recover");accept(o);phase=ColorFloorPhase.RECOVERING;live.clear();}public synchronized void close(OperationId o){if(phase!=ColorFloorPhase.RECOVERING&&phase!=ColorFloorPhase.FINISHING)throw new IllegalStateException("cannot close");accept(o);phase=ColorFloorPhase.CLOSED;}
 private void mutate(OperationId o,ColorFloorPhase n){if(phase!=ColorFloorPhase.DISABLED)throw new IllegalStateException("cannot open");accept(o);phase=n;}private void require(ColorFloorPhase e,OperationId o){if(phase!=e)throw new IllegalStateException("illegal phase");acceptable(o);}private void acceptable(OperationId o){Objects.requireNonNull(o);if(!id.equals(o.matchId())||ops.contains(o)||o.sequence()<=seq)throw new IllegalStateException("stale or duplicate operation");}private long seq;private void accept(OperationId o){acceptable(o);ops.add(o);seq=o.sequence();}
}
