package com.ciaac.minecraft.minigames.isolation;

public enum PlayerStateFacet {
    INVENTORY,
    ITEM_METADATA_AND_DURABILITY,
    ARMOR,
    OFF_HAND,
    CURSOR,
    ENDER_CHEST,
    EXPERIENCE,
    HEALTH,
    FOOD_AND_SATURATION,
    POTION_EFFECTS,
    FIRE_FREEZE_AND_AIR,
    GAMEMODE,
    FLIGHT,
    LOCATION_AND_WORLD,
    VANILLA_STATISTICS,
    ADVANCEMENTS,
    ECONOMY,
    PERMISSIONS,
    CLAIMS_AND_HOMES,
    SCOREBOARDS_AND_COOLDOWNS,
    TEMPORARY_WORLD_BLOCKS_AND_ENTITIES
}
