package com.ciaac.minecraft.minigames.elytrarings;
import com.ciaac.minecraft.minigames.hotpotato.OperationId;import java.time.*;import java.util.*;
/** Ordered checkpoint domain; adapters must reject movement before calling checkpoint. */
public final class ElytraRingsGame{private final UUID id,player;private final ElytraRingsConfig config;private final Set<OperationId> ops=new HashSet<>();private final List<Duration> splits=new ArrayList<>();private ElytraRingsPhase phase=ElytraRingsPhase.DISABLED;private int next=1,resets;private Instant started;private ElytraRingsResult result;private long seq;
 public ElytraRingsGame(UUID id,UUID player,ElytraRingsConfig c){this.id=Objects.requireNonNull(id);this.player=Objects.requireNonNull(player);config=Objects.requireNonNull(c);}
 public synchronized ElytraRingsPhase phase(){return phase;}public synchronized int nextRing(){return next;}public synchronized List<Duration> splits(){return List.copyOf(splits);}public synchronized Optional<ElytraRingsResult> result(){return Optional.ofNullable(result);}public ElytraCourseRevision course(){return config.course();}
 public synchronized void open(OperationId o){if(phase!=ElytraRingsPhase.DISABLED)throw new IllegalStateException("cannot open");accept(o);phase=ElytraRingsPhase.WAITING;}public synchronized void start(Instant now,OperationId o){require(ElytraRingsPhase.WAITING,o);started=Objects.requireNonNull(now);accept(o);phase=ElytraRingsPhase.RUNNING;}
 public synchronized void checkpoint(int order,Instant now,OperationId o){require(ElytraRingsPhase.RUNNING,o);if(order!=next)throw new IllegalArgumentException("ring must be reached in order");if(now.isBefore(started)||now.isAfter(started.plus(config.timeout())))throw new IllegalStateException("run timed out");accept(o);splits.add(Duration.between(started,now));if(next==config.course().rings().size()){result=new ElytraRingsResult(id,config.course().revision(),player,true,splits.get(splits.size()-1),splits,resets,"COMPLETED");phase=ElytraRingsPhase.FINISHING;}else next++;}
 public synchronized void reset(Instant now,OperationId o){require(ElytraRingsPhase.RUNNING,o);accept(o);resets++;next=1;splits.clear();started=Objects.requireNonNull(now);}public synchronized void invalidate(Instant now,OperationId o){require(ElytraRingsPhase.RUNNING,o);Objects.requireNonNull(now);if(now.isBefore(started))throw new IllegalArgumentException("invalid finish time");accept(o);result=new ElytraRingsResult(id,config.course().revision(),player,false,Duration.between(started,now),splits,resets,"INVALIDATED");phase=ElytraRingsPhase.FINISHING;}public synchronized void recover(OperationId o){if(phase==ElytraRingsPhase.DISABLED||phase==ElytraRingsPhase.CLOSED)throw new IllegalStateException("cannot recover");accept(o);phase=ElytraRingsPhase.RECOVERING;}public synchronized void close(OperationId o){if(phase!=ElytraRingsPhase.RECOVERING&&phase!=ElytraRingsPhase.FINISHING)throw new IllegalStateException("cannot close");accept(o);phase=ElytraRingsPhase.CLOSED;}
 private void require(ElytraRingsPhase p,OperationId o){if(phase!=p)throw new IllegalStateException("illegal phase");acceptability(o);}private void accept(OperationId o){acceptability(o);ops.add(o);seq=o.sequence();}private void acceptability(OperationId o){Objects.requireNonNull(o);if(!id.equals(o.matchId())||ops.contains(o)||o.sequence()<=seq)throw new IllegalStateException("stale or duplicate operation");}}
